Total Revenue =

SUM(

fact_customer_activity[revenue]

)

------------------------------------------------

Paid Customers =

SUM(

fact_customer_activity[paid_customers]

)

------------------------------------------------

Revenue Per Customer =

DIVIDE(

[Total Revenue],

[Paid Customers]

)

------------------------------------------------

Average Revenue Per User =

DIVIDE(

[Total Revenue],

DISTINCTCOUNT(

dim_customer[customer_id]

)

)