Revenue MTD =

TOTALMTD(

[Total Revenue],

dim_date[full_date]

)

--------------------------------

Revenue QTD =

TOTALQTD(

[Total Revenue],

dim_date[full_date]

)

--------------------------------

Revenue YTD =

TOTALYTD(

[Total Revenue],

dim_date[full_date]

)

--------------------------------

Previous Month Revenue =

CALCULATE(

[Total Revenue],

PREVIOUSMONTH(

dim_date[full_date]

)

)